# Generated by Django 3.2.5 on 2021-10-12 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='7', editable=False, max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('CardId', models.CharField(blank=True, max_length=20)),
                ('YearofBirth', models.IntegerField(blank=True)),
                ('school', models.CharField(max_length=256)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('times_of_scan', models.IntegerField(default=0, editable=False)),
                ('last_scanned', models.DateTimeField(blank=True)),
            ],
        ),
    ]
