# Generated by Django 3.2.5 on 2021-10-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user_id',
            field=models.CharField(default='kfbkj5av', editable=False, max_length=8),
        ),
    ]
