# Generated by Django 3.2.5 on 2021-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0002_auto_20211013_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='user_id',
            field=models.CharField(default='vw133ysu', editable=False, max_length=8),
        ),
    ]
